"""
News Intelligence - Briefing Generator
Generates structured Markdown briefings from scored/deduped/enriched items.
"""

import json
from pathlib import Path
from datetime import datetime


def generate_briefing(items: list[dict], config: dict) -> str:
    """Generate a Markdown briefing from items."""
    date_str = datetime.now().strftime("%Y-%m-%d")
    general = config.get("general", {})
    lang = general.get("language", "pt")

    # Group by score ranges
    critical = [i for i in items if i.get("score", 0) >= 8]
    relevant = [i for i in items if 6 <= i.get("score", 0) < 8]
    marginal = [i for i in items if general.get("score_threshold", 5) <= i.get("score", 0) < 6]

    # Stats
    sources_used = set(i.get("source", "") for i in items)

    lines = []
    lines.append(f"# 📰 Daily Briefing — {date_str}")
    lines.append("")

    if lang == "pt":
        lines.append(f"*Gerado automaticamente pela News Intelligence da Agência*")
    else:
        lines.append(f"*Auto-generated by Agency News Intelligence*")
    lines.append("")

    # Critical
    if critical:
        if lang == "pt":
            lines.append("## 🔴 Crítico (8-10)")
        else:
            lines.append("## 🔴 Critical (8-10)")
        lines.append("")
        for item in critical:
            lines.append(_format_item(item, lang))
        lines.append("")

    # Relevant
    if relevant:
        if lang == "pt":
            lines.append("## 🟡 Relevante (6-7)")
        else:
            lines.append("## 🟡 Relevant (6-7)")
        lines.append("")
        for item in relevant:
            lines.append(_format_item(item, lang))
        lines.append("")

    # Marginal
    if marginal:
        if lang == "pt":
            lines.append("## ⚪ Marginal (5)")
        else:
            lines.append("## ⚪ Marginal (5)")
        lines.append("")
        for item in marginal:
            lines.append(_format_item(item, lang))
        lines.append("")

    # Stats
    lines.append("## 📊 Estatísticas")
    lines.append("")
    if lang == "pt":
        lines.append(f"- Fontes consultadas: {len(sources_used)}")
        lines.append(f"- Itens entregues: {len(items)}")
        lines.append(f"- Críticos: {len(critical)}")
        lines.append(f"- Relevantes: {len(relevant)}")
        lines.append(f"- Marginais: {len(marginal)}")
    else:
        lines.append(f"- Sources checked: {len(sources_used)}")
        lines.append(f"- Items delivered: {len(items)}")
        lines.append(f"- Critical: {len(critical)}")
        lines.append(f"- Relevant: {len(relevant)}")
        lines.append(f"- Marginal: {len(marginal)}")
    lines.append("")

    return "\n".join(lines)


def _format_item(item: dict, lang: str = "pt") -> str:
    """Format a single item for the briefing."""
    title = item.get("title", "Untitled")
    url = item.get("url", "")
    score = item.get("score", 0)
    source = item.get("source", "")
    summary = item.get("summary", "")
    context = item.get("context", "")
    sources = item.get("all_sources", [source])

    lines = []
    source_label = " + ".join(sources) if len(sources) > 1 else source

    if url:
        lines.append(f"- **[{title}]({url})** (score: {score:.0f}) — {source_label}")
    else:
        lines.append(f"- **{title}** (score: {score:.0f}) — {source_label}")

    if summary:
        lines.append(f"  {summary}")
    if context:
        lines.append(f"  *Contexto: {context}*")

    return "\n".join(lines)


def save_briefing(content: str, config: dict):
    """Save briefing to file and optionally to memory."""
    date_str = datetime.now().strftime("%Y-%m-%d")
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Save to data/briefings
    brief_dir = Path(config.get("delivery", {}).get("file", {}).get("path", "data/briefings"))
    brief_dir.mkdir(parents=True, exist_ok=True)
    filepath = brief_dir / f"briefing_{ts}.md"
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[Briefing] Saved to {filepath}")

    # Save to memory/briefings
    mem_enabled = config.get("delivery", {}).get("memory", {}).get("enabled", False)
    if mem_enabled:
        mem_path = Path(config["delivery"]["memory"].get("save_to", "memory/briefings"))
        mem_path.mkdir(parents=True, exist_ok=True)
        mem_file = mem_path / f"{date_str}.md"
        with open(mem_file, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"[Briefing] Saved to memory: {mem_file}")

    return str(filepath)


if __name__ == "__main__":
    import sys
    config_path = sys.argv[1] if len(sys.argv) > 1 else "config/sources.json"
    input_path = sys.argv[2] if len(sys.argv) > 2 else "data/enriched"

    with open(config_path, encoding="utf-8") as f:
        config = json.load(f)

    raw_files = sorted(Path(input_path).glob("enriched_*.json"))
    if not raw_files:
        # Try deduped
        raw_files = sorted(Path("data/deduped").glob("deduped_*.json"))
    if not raw_files:
        # Try scored
        raw_files = sorted(Path("data/scored").glob("scored_*.json"))
    if not raw_files:
        print("No data found")
        sys.exit(1)

    with open(raw_files[-1], encoding="utf-8") as f:
        items = json.load(f)

    briefing = generate_briefing(items, config)
    save_briefing(briefing, config)
    print(f"\n{briefing}")
